version: '3.3'

networks:
  smartTribune_docker:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: 'smartTribune_docker-server'
    ports:
      - '8101:80'
    working_dir: /var/www/html
    environment:
      - 'DATABASE_URL=mysql://admin:25021964@db_server:3306/smartTribune?serverVersion=10.5'
    volumes:
      - ./sources:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      - db_server
    networks:
      - smartTribune_docker

  db_server:
    image: mariadb:10.5.9
    container_name: 'smartTribune_docker-db'
    restart: always
    ports:
      - '33016:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '25021964'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '25021964'
      MYSQL_DATABASE: 'smartTribune'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - smartTribune_docker

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: 'smartTribune_docker-db-admin'
    ports:
      - '8102:80'
    environment:
      PMA_HOST: db_server
    depends_on:
      - db_server
    volumes:
      - db_admin_data:/var/www/html
    networks:
      - smartTribune_docker

volumes:
  db_data:
  db_admin_data:
